### ISSUE TITLE
Does not work with react-refresh plugin

### ISSUE THREAD

**Issue by sali0** [gxmari007/vite-plugin-eslint#1]
Hey there. I just installed this plugin and when running 'yarn dev', I get this error:
```
6:47:40 PM [vite] Internal server error: No ESLint configuration found in /.
  Plugin: vite:eslint
  File: /@react-refresh
```

**Comment by gxmari007** [comment]
You need `.eslintrc` config file in project.

**Comment by sali0** [comment]
I did have the .eslintc, which was why it was confusing. When I started using the Rollup plugin it was working (not perfectly though).

**Comment by gxmari007** [comment]
You can take a look at this project [https://github.com/qinghuanI/vite-react-app](https://github.com/qinghuanI/vite-react-app)

**Comment by Gelio** [comment]
I have just encountered the same problem. The fix was to tell the plugin to not lint `/@react-refresh`. This can be done by either mentioning it in the `exclude` array:

```ts
    eslintPlugin({
      exclude: ["node_modules", "/@react-refresh"],
    }),
```

or having an `include` section with only specific files from the `src` directory:

```ts
    eslintPlugin({
      include: "src/**/*.{js,jsx,ts,tsx}",
    }),
```
