### ISSUE TITLE
完全看不出来运行效果，也没有提示任何错误

### ISSUE THREAD

**Issue by bhabgs** [gxmari007/vite-plugin-eslint#10]
![image](https://user-images.githubusercontent.com/19221378/126428963-0e6b75c1-1dbe-41af-a935-22c4a4b3b329.png)

**Comment by gxmari007** [comment]
发一下你的 eslintrc 配置和 vite.config

**Comment by bhabgs** [comment]
这块，我运行的是 [您的template](https://github.com/gxmari007/vite-plugin-eslint/tree/main/example/vue)
是不是因为 vite 是通过浏览器去解析模块，无法在node 端扫描啊？

**Comment by gxmari007** [comment]
是啊，开发模式需要打开浏览器才能看到报错，打包模式可以立即看到检查结果

**Comment by bhabgs** [comment]
已经解决了。感谢你的分享🙏
![image](https://user-images.githubusercontent.com/19221378/126610256-c9788b0e-7ad3-4ac5-8a0e-e00e1d0ba0ca.png)
