### ISSUE TITLE
add support for eslint 8.x

### ISSUE THREAD

**Issue by pzmosquito** [gxmari007/vite-plugin-eslint#22]

**Comment by ModyQyW** [comment]
I try to add support for eslint@8 in [@modyqyw/vite-plugin-eslint](https://github.com/ModyQyW/vite-plugin-eslint).

**Comment by ramicohen303** [comment]
Is there an update on this? npm install fails when using eslint 8.x.

**Comment by michaelpumo** [comment]
You can get this going with ESLint 8 by running `npm i --force` ...but then that's probably not wise in every situation.

**Comment by brockjord** [comment]
Latest version (1.5.1) still lists eslint 7 as a peer dep. Forcing the install doesn't appear to have any negative impact in my case, but would be nice to have eslint 8 support.

**Comment by gxmari007** [comment]
fixed this warning
