### ISSUE TITLE
Add eslintPath option

### ISSUE THREAD

**Issue by otakustay** [gxmari007/vite-plugin-eslint#23]
Reference https://github.com/ModyQyW/vite-plugin-stylelint/issues/2 , maybe we can provide an `eslintPath` option to allow user to specify a custom eslint implementation path.

**Comment by nyan-left** [comment]
This would be great!

**Comment by ModyQyW** [comment]
`eslintPath` option and `eslint` dynamic import have launched on `@modyqyw/vite-plugin-eslint@1.1.0-beta.0`. Take a try and give me some feedback. :D

**Comment by chatondearu** [comment]
@ModyQyW why don't make a PR into this projet :p that will be awesome !
