### ISSUE TITLE
option: show errors as warnings?

### ISSUE THREAD

**Issue by d9k** [gxmari007/vite-plugin-eslint#24]
Need ability to show errors as warnings for faster prototyping.

**Comment by d9k** [comment]
It's possible to use [bfanger](https://github.com/bfanger)/[eslint-plugin-only-warn](https://github.com/bfanger/eslint-plugin-only-warn) for this purpose.

**Comment by ModyQyW** [comment]
`emitErrorAsWarning` option have launched on @modyqyw/vite-plugin-eslint@1.2.0. Take a try and give me some feedback. :D

**Comment by gxmari007** [comment]
use `1.6.0` and set `failOnError` false, will use `console.log` printed
