### ISSUE TITLE
v1.5.0 regression - No File Matching error

### ISSUE THREAD

**Issue by jzs11** [gxmari007/vite-plugin-eslint#27]
Repo: https://github.com/jzs11/vite-regression-playground
run `npm i` and `npm run build`

You shall be able to see the following error:
![image](https://user-images.githubusercontent.com/2770401/164237328-593782ac-60a9-4acc-9717-3a8ba66cb9d5.png)

Downgrade to v1.4.0 the problem is gone.

Thanks!

**Comment by gxmari007** [comment]
sorry i made a mistake, updated to 1.5.1 will fixed.

**Comment by jzs11** [comment]
no worries, thanks for the awesome work :)

**Comment by jzs11** [comment]
Hi dude,

I updated to the latest version, the playground repo is working fine, however, my main working repo still seems to have some problems

![image](https://user-images.githubusercontent.com/2770401/164324851-e738d43b-aa8b-4011-8056-3d526674da15.png)

Any advice would be really appreciated, thanks.

**Comment by jzs11** [comment]
Problem is gone after I installed the following extensions, closing the ticket. thanks for your help !
`"eslint-config-standard": "^17.0.0",`
`"eslint-plugin-standard": "^5.0.0",`

**Comment by amykapernick** [comment]
I'm still having this issue with `v1.6.0`, on an astro site. Have stripped it all the way back and confirmed it's the eslint plugin that is causing the issue, adding the standard config doesn't help

https://codesandbox.io/s/quirky-microservice-3zc032?file=/astro.config.mjs
