### ISSUE TITLE
未引用的文件是否也可以检查出错误并显示在浏览器上 ?

### ISSUE THREAD

**Issue by darkmirrors** [gxmari007/vite-plugin-eslint#33]
## 问题描述
目前开发环境，引用到的文件是可以提示到错误到浏览器的，但一些没有引用到的文件，则不会报错。

## 期望效果
是否可以加入全局检查的配置？
开启的时候做全局检查，并把错误信息打印到浏览器上？

## 说明
这样做的好处在于，可以把问题前置，不需要在 precommit 或者 build的时候才发现问题

**Comment by gxmari007** [comment]
按 vite 的机制是没办法做到，你说的这个似乎可以用开启 cache 的模式，更改过的文件每次检查都会读取缓存，只是还不完善，没缓存到本地😔
