### ISSUE TITLE
vite build failed with vite-plugin-eslint 1.8.0

### ISSUE THREAD

**Issue by aguegu** [gxmari007/vite-plugin-eslint#37]
failure in `npm run build` (vite build)

```
[commonjs--resolver] Cannot read config file: ***********************/node_modules/@css-render/vue3-ssr/.eslintrc.js
Error: Cannot find module '@rushstack/eslint-config/patch/modern-module-resolution'
```

even after `@rushstack/eslint-config` installed, the error would be

```
[commonjs--resolver] Failed to load config "@css-render/eslint-config/base" to extend from.
Referenced from:***********************/node_modules/@css-render/vue3-ssr/.eslintrc.js
```
rolling back to 1.7.0 would just work fine.

**Comment by nevil2** [comment]
I have same issue with a different package:
ERROR  [vite-plugin-eslint] Failed to load plugin 'prettier' declared in 'node_modules/@vue-leaflet/vue-leaflet/package.json': Cannot find module 'eslint-plugin-prettier'
Rolled back to 1.7.0

**Comment by mikouaji** [comment]
I have a similar issue with a different package
```
[error] [commonjs--resolver] Failed to load config "./.config/eslint.config" to extend from.
Referenced from: ***/node_modules/tippy.js/package.json
file: ***/node_modules/tippy.js/dist/tippy.esm.js
```
Also rolled back to `1.7.0`

**Comment by Aslam97** [comment]
I have same issue. fix by replacing **include** value

```
plugins: [
   eslint({ include: '/.(js|vue)$/' })
]
```

**Comment by gxmari007** [comment]
`include` and `exclude` option types are now restricted to `string` or `string[]`

**Comment by tfonfara** [comment]
I can confirm the bugfix 👍
