### ISSUE TITLE
Exclude the json files but not working

### ISSUE THREAD

**Issue by mogocat** [gxmari007/vite-plugin-eslint#4]
eslintPlugin({ exclude: ['node_modules', '*.json'], cache: false })

This is my configuration, but the json files still be checked, and trigger an error about the json format.

 Parsing error: /Users/alfred/develop/pds_vue/src/utils/particles.json: Missing semicolon (2:12)

 {
  "autoPlay": true
}

**Comment by gxmari007** [comment]
En...should be set like this `{ exclude: ['node_modules', 'src/**/*.json'] }`, your setting only affect the root directory json file.
