### ISSUE TITLE
Default exclude path doesnt seem to work sometimes

### ISSUE THREAD

**Issue by brense** [gxmari007/vite-plugin-eslint#40]
Hello! I discovered recently that there's an issue when building a project that includes `@popperjs` I got an error:
```bash
Error: Failed to load config "./.config/eslint.config" to extend from.
```
That I eventually tracked down to `vite-plugin-eslint`...
When I changed my vite config from:
```ts
import eslint from 'vite-plugin-eslint'

export default defineConfig({
  ...otherConfig,
  plugins: [...otherPlugins, eslint()]
})
```
To this:
```ts
import eslint from 'vite-plugin-eslint'

export default defineConfig({
  ...otherConfig,
  plugins: [...otherPlugins, eslint({
    exclude: ['**/node_modules/**']
  })]
})
```
The build worked fine!

Not sure if the same issue exsists for other packages besides `@popperjs`. Here's the original comment on the `@popperjs` github: https://github.com/floating-ui/floating-ui/issues/1485#issuecomment-1217502942

**Comment by gxmari007** [comment]
`v1.8.1` has fixed.🙂

**Comment by brense** [comment]
Tested, works for my use-case! Thank you kindly sir!
