### ISSUE TITLE
 ERROR  Cannot restart nuxt:  Failed to import ESLint, do you install or configure eslintPath?

### ISSUE THREAD

**Issue by szulcus** [gxmari007/vite-plugin-eslint#56]
I am using this plugin for Nuxt 3 app. Here is my `nuxt.config.ts`:
```ts
import eslint from 'vite-plugin-eslint';

export default defineNuxtConfig({
	// ...
	vite: {
		plugins: [
			eslint({
				fix: true,
				include: ['./**/*.{js,ts,vue}'],
				eslintPath: './eslint/eslint.json',
				// eslintPath: '@frontend/nuxt-layer-base/assets/linters/.eslintrc.json',
			}),
		],
	},
});
```
![image](https://user-images.githubusercontent.com/48328739/215843795-ec14ca97-8ab2-4b74-806f-3d6a6563148b.png)

What can I do wrong?

**Comment by ruiaraujo012** [comment]
Same here, did you find a solution?

**Comment by szulcus** [comment]
I gave up the `eslintPath` field (not sure about slime for config file) and created a new project with the ESLint configuration as NPM package: https://eslint.org/docs/latest/extend/shareable-configs. Remember about `eslint-config` prefix in the package name.

**Comment by ruiaraujo012** [comment]
Ok, thanks anyway.

**Comment by andrewmelnyk** [comment]
I am having the same issue but I am now wondering is this even meant to point toward an .eslintrc file or the path to the actual eslint code like inside of node_modules?

**Comment by andrewmelnyk** [comment]
@szulcus did you manage to find a way to use the shared config with the vite plugin? or are you saying you are simply importing the shared config into your eslintrc.json file?

**Comment by szulcus** [comment]
@andrewmelnyk yes exactly. In `.eslintrc.json`:
```json
{
	"root": true,
	"extends": "<package-with-eslint-configuration>"
}
```

**Comment by andrewmelnyk** [comment]
@szulcus That's too bad that it doesn't work with the vite-plugin it would be nice to be able to use that shared config with the plugin. I ended up doing the same as you in my project using a shared config but would have liked to integrate it with this plugin.
