### ISSUE TITLE
How to close throwOnWarning

### ISSUE THREAD

**Issue by LHNfromTJ** [gxmari007/vite-plugin-eslint#6]
Hello：
  When using vite, there are two eslint plugins @rollup/plugin-eslint and vite-plugin-eslint. When I use vite-plugin-eslint, if there is a warning in my code, then vite will stop Compile and display the warning message on the page. What I want is to not stop the compilation of vite and turn off the warning message in the warning state, just like the throwOnWarning option in @rollup/plugin-eslint. How do I do it?

**Comment by gxmari007** [comment]
Has supported
